apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJlSEpwYm1GME9tZG9jRjlLV21sak5HODNUSEY2YWpsVGVsTTRlVEJKTWxKRVVEWlJkSGx5VjBreGVIQm1XVW9nIiwKICAgICAgImVtYWlsIjogInh4eC5yaW5hdEB5YW5kZXgucnUiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson
