apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinemaabyss-ingress
  namespace: cinemaabyss
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false" 
spec:
  rules:
    - host: cinemaabyss.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-service # API Gateway
                port:
                  number: 8000
          
          - path: /api/events
            pathType: Prefix
            backend:
              service:
                name: proxy-service # API Gateway
                port:
                  number: 8000